### ISSUE TITLE
How to dynamically hide drift?

### ISSUE THREAD

**Issue by JaLe29** [chardmd/react-drift#20]
Is there any way how to hide drift?

Looks like that is inject somehow into dom, so I can't remove it using single condition like:

```
const driftElement = showDrift ? <Drift appId={DRIFT_KEY} /> : null
```

Once it is visible, it is visible forever :-)

**Comment by chardmd** [comment]
I just recently merged a recent PR for adding styles in this component, which is now available in the latest version. try it out.

**Comment by abohannon** [comment]
@JaLe29 You're correct. Since the initial mount adds the script to the DOM, dynamically rendering `null` after that won't affect the widget. What you need to do is use the `drift.api.widget.hide()` method. As a matter of fact I'm working on a solution right now in my own project. Below is what I have so far. This works when the widget is only the chat bubble, but not when it has the entry message displayed. Still need to experiment and see how to close that version of the widget. 

At some point I plan to think through how to add this to this repo. Ideally it would be passed in via the `eventHandlers` prop but I don't think this prop will work as people assume it will. Since it's adding JS to the DOM based on the event, the scoping is completely lost so you can't reference variables from your React component, for example. I realized this while trying to add an analytics function, as well as a dispatch for my redux store. This is a separate issue, so I'll open one.

Hope this helps. Also, as @chardmd mentioned, you could probably also dynamically hide the component via the `styles` prop (I haven't tried it yet), but I'd prefer to use the drift api.

```
const DriftWrapper = props => {
  const isOpen = useSelector(({ drift }) => drift.isOpen)

  useEffect(() => {
    if (window.drift && window.drift.api) {
      if (isOpen) {
        window.drift.api.widget.show()
      } else {
        window.drift.api.widget.hide()
      }
    }
  }, [isOpen])

  const eventHandlers = [
    {
      event: 'conversation:playbookClicked',
      function: () => trackButtonClick(CHAT, 'chat bubble', FIXED),
    },
  ]

  return <Drift eventHandlers={eventHandlers} {...props} />
}
```

**Comment by rashad** [comment]
@abohannon a little over a year later, any chance you could share with us how you finally handled things ? 😇
